---
name: safe

features:
  converge_variables: true

releases:
- name: vault
  version: latest
- name: consul
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name:      vault
  instances: 3
  azs:       [z1]
  vm_type:   hart
  stemcell:  default

  # vault requires a persistent disk, otherwise
  # you will lose all of your stored secrets.
  persistent_disk_type: default

  networks:
  - name: bridge
    static_ips:
    - 192.168.1.36
    - 192.168.1.37
    - 192.168.1.38

  jobs:
  - name: vault
    release: vault
    properties:
      vault:
      # from consul block
            # tls_skip_verify = "true"
            # tls_min_version = "tls12"
            # tls_skip_verify = "false"
            # tls_ca_file     = "/var/vcap/jobs/vault/tls/peer/ca.pem"
            # tls_cert_file   = "/var/vcap/jobs/vault/tls/peer/cert.pem"
            # tls_key_file    = "/var/vcap/jobs/vault/tls/peer/key.pem"
        config: |
          disable_mlock = 1
          backend "consul" {
            path = "vault/"
            check_timeout = "5s"
            max_parallel = "128"

            scheme = "http"
          }

          listener "tcp" {
            address = "0.0.0.0:443"
            tls_cert_file   = "/var/vcap/jobs/vault/tls/vault/cert.pem"
            tls_key_file    = "/var/vcap/jobs/vault/tls/vault/key.pem"
            tls_min_version = "tls12"
          }

          ui = false
      tls:
      - name: vault
        cert: ((vault-tls.certificate))((/pki/mtls_cas/vault_ca.certificate))
        key: ((vault-tls.private_key))
  - name: consul
    release: consul
    properties:
      consul:
        server: false
        datacenter: yao
        domain: skelter
    consumes:
      consul_servers: { from: consul, deployment: raft }

update:
  canaries:          0
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

variables:
- name: /pki/mtls_cas/vault_ca
  type: certificate
  options:
    is_ca: true
    ca: /pki/root_ca
    common_name: Vault intermediate CA for mtls
- name: vault-tls
  type: certificate
  options:
    ca: /pki/mtls_cas/vault_ca
    common_name: Vault tls certificate for server
    alternative_names:
    - active.vault.service.skelter
    - vault.service.skelter
    - standby.vault.service.skelter
    - localhost

